### ISSUE TITLE
Pin poetry version in pyproject.toml

### ISSUE THREAD

**Issue by adubovik** [epam/ai-dial-analytics-realtime#95]
Consider defining poetry version in `pyproject.toml` as a [single source of truth](https://python-poetry.org/docs/pyproject/#requires-poetry):

```toml
[build-system]
requires = ["poetry-core==1.6.1"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
requires-poetry = "==1.6.1"
```

Modify `Makefile` and `README` is needed accordingly. 

Make sure that this approach doesn't force the user to install any particular version of `poetry` **globally**.
